version: '3.3'

services:
  smsgw:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    restart: unless-stopped
    devices:
      - "/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0:/dev/gsmmodemMySim"
    environment:
      - SMSGW_DB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SMSGW_DB_HOST=db
      - SMSGW_DB_DATABASE=${MYSQL_DATABASE}
      - SMSGW_DB_USER=${MYSQL_USER}
      - SMSGW_DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '2525:2525'
    depends_on:
      - db
    volumes:
      # Note also copied in image, but easier to use a volume during development(no rebuild required)
      - type: bind
        source: ./app
        target: /usr/src/app

  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=smsgw
      - MYSQL_USER=smsgw
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
